jsk-ros-pkg/jsk_3rdparty

- jsk_ros_patch/collada_urdf_jsk_patch/Makefile
fix for https://github.com/jsk-ros-pkg/jsk_common/pull/1069
> collada_urdf_jsk_patch/Makefile: use catkin build to compile robot_model

- 3rdparty/assimp_devel/package.xml
- 3rdparty/ff/package.xml
http://jenkins.ros.org/job/ros-jade-ff_binarydeb_vivid_i386/52/
```
[ 50%] Generating installed
make -f /tmp/buildd/ros-jade-ff-2.0.3-0vivid-20150816-0647/Makefile MD5SUM_DIR=/tmp/buildd/ros-jade-ff-2.0.3-0vivid-20150816-0647
make[5]: Entering directory '/tmp/buildd/ros-jade-ff-2.0.3-0vivid-20150816-0647/obj-i686-linux-gnu'
mkdir -p build
if [ ! -f /tmp/buildd/ros-jade-ff-2.0.3-0vivid-20150816-0647/FF-v2.3.tgz.md5sum ]; then echo "Error: Couldn't find md5sum file /tmp/buildd/ros-jade-ff-2.0.3-0vivid-20150816-0647/FF-v2.3.tgz.md5sum" && false; fi
/opt/ros/jade/share/ros/core/rosbuild/bin/download_checkmd5.py http://github.com/jsk-ros-pkg/archives/raw/master/FF-v2.3.tgz build/FF-v2.3.tgz `awk {'print $1'} /tmp/buildd/ros-jade-ff-2.0.3-0vivid-20150816-0647/FF-v2.3.tgz.md5sum`
[rosbuild] …
```
> add ca-certificates for https download

- 3rdparty/nlopt/Makefile
Fixes #39
This is because there is an error while compiling nlopt with octave on
Indigo Ubuntu 14.04.
> [nlopt] Stop compiling with octave

- 3rdparty/voice_text/text2wave
Enable text2wave using VoiceText other than pr2 robots.
Previously, `c2` machine name is hard-coded.
Using this PR, text2wave can used for
- local machine voicetext
- hostname other than c2
Default behavior may be not changed (remote machine mode and hostname is `c2`).
To specify these options, I used environments instead of arguments for text2wave 
because it is difficult to add argument from soundplay_node.py:
http://docs.ros.org/jade/api/sound_play/html/soundplay__node_8py_source.html
How to use
```
<launch>
<node pkg="sound_play" type="soundplay_node.py" name="robotsound_jp" output="screen">
<env name="PATH" value="$(find voice_text):$(env PATH)" />
<env name="VOICETEXT_TEXT2WAV_USE_LOCAL_MODE" value="tru" />
<remap from="robotsound" to="robotsound_jp" />
</node>
</launch>
``` …
> Enable text2wave using VoiceText other than pr2 robots.

- 3rdparty/libsiftfast/CMakeLists.txt
- 3rdparty/libsiftfast/Makefile
Modified:
- 3rdparty/libsiftfast/CMakeLists.txt
> [libsiftfast] Use PYTHON_INSTALL_DIR to install python module with catkin

- 3rdparty/downward/package.xml
```
[pddl_planner:make] /opt/ros/kinetic/share/downward/src/search/unitcost: 4: /opt/ros/kinetic/share/downward/src/search/unitcost: gawk: not found
```
> add gawk to run_depends

- jsk_ros_patch/collada_urdf_jsk_patch/Makefile
- jsk_ros_patch/collada_urdf_jsk_patch/README.md
- jsk_ros_patch/collada_urdf_jsk_patch/use_assimp_devel.patch
https://github.com/ros/robot_model/pull/183
ros/robot_model@3e5a220
> [collada_urdf_jsk_patch] update patch

- rosping/CMakeLists.txt
for http://build.ros.org/job/Kbin_uX32__rosping__ubuntu_xenial_i386__binary/4/display/redirect
> rosping: CMakeLists.txt: fix for cmake 3.5.1

- opt_camera/cfg/OptNM33Camera.cfg
To fix error reported on #90 
Briefly `grep`ped entire jsk-ros-pkg and confirmed that updating this parameter should not have any side-effect.
> [opt_camera][OptNM33Camera.cfg] param "4view" does not follow ROS convention

- opt_camera/cfg/OptNM33Camera.cfg
Reverts jsk-ros-pkg/jsk_3rdparty#91
> Revert "[opt_camera][OptNM33Camera.cfg] param "4view" does not follow ROS convention"

- .travis.yml
- 3rdparty/libsiftfast/patches/01.fix_python_binding.patch
`libsiftfast` is written for python2 and can be successfully installed with python2.
However this package finds and uses python3 (not 2) first on environment where both python2 and 3 are installed.
(In new travis environment both python2 and 3 seems to be installed)
This issue is fixed in this PR by setting version 2 on `find_package` python.
This should close https://github.com/jsk-ros-pkg/jsk_3rdparty/issues/42 .
> [libsiftfast] prefer python 2 to find

- jsk_ros_patch/laser_filters_jsk_patch/src/laser_scan_filters.cpp
These macros, deprecated for now 8 years, will be removed in the next ROS release (ROS Melodic)
This change will allow the code to keep compiling on future ROS versions
> update to use non deprecated pluginlib macro

- 3rdparty/downward/package.xml
Reverts jsk-ros-pkg/jsk_3rdparty#115
we do not have `g++` rosdep keys..
> Revert "use g++ instead of g++-static"

- 3rdparty/voice_text/CMakeLists.txt
`text2wave` Was wrongly  installed to `CATKIN_PACKAGE_LIB_DESTINATION`
The launch file is assumed that it is installed under `rospack find voice_text`/bin
https://github.com/jsk-ros-pkg/jsk_3rdparty/blob/2.1.10/3rdparty/voice_text/launch/voice_text.launch#L29
> Fix install directory of text2wave to ./lib -> ./bin

- respeaker_ros/launch/sample_respeaker.launch
In this PR, I add some `arg` to `sample_respeaker.launch` so that we can include this launch file in other launch file.
> Make sample_respeaker.launch re-usable

- 3rdparty/libsiftfast/patches/01.fix_python_binding.patch
> enable to compile libsiftfast with current numpy.get_include()

- respeaker_ros/scripts/speech_to_text.py
currently, `speech_to_text` only check one speaking action server to identify whether robot is speaking or not.
However, PR2 uses two action server to speak English and Japanese (`robotsound` and `robotsound_jp`),
and Fetch uses, too (`sound_play` and `robotsound_jp`).
I change to pass speak action server names to `speech_to_text` node to check all speaking servers.
This system is now working in Fetch15.
cc. @708yamaguchi
> [respeaker_ros] add tts_action_names param: do not listen when the robot is speaking either japanese or english

- dialogflow_task_executive/package.xml
http://build.ros.org/job/Kdoc__jsk_3rdparty__ubuntu_xenial_amd64/7/display/redirect
build failing because of std_msgs missing.
```
- message_generation
CMake Error at /tmp/ws/build_isolated/dialogflow_task_executive/cmake/dialogflow_task_executive-genmsg.cmake:3 (message):
Could not find messages which
'/tmp/ws/src/jsk_3rdparty/dialogflow_task_executive/msg/DialogResponse.msg'
depends on.  Did you forget to specify generate_messages(DEPENDENCIES ...)?
Cannot locate message [Header]: unknown package [std_msgs] on search path
[{{'dialogflow_task_executive':
['/tmp/ws/src/jsk_3rdparty/dialogflow_task_executive/msg']}}]
Call Stack (most recent call first):
/opt/ros/kinetic/share/genmsg/cmake/genmsg-extras.cmake:307 (include)
CMakeLists.txt:91 (generate_messages)
```
> add std_msgs in package.xml

- rostwitter/scripts/tweet.py
I remove `print(data)` debug line to suppress log output.
> remove debug print line in rostwitter to suppress log

- 3rdparty/libcmt/package.xml
Related to https://github.com/jsk-ros-pkg/jsk_recognition/issues/2474
On current master branch, `libcmt` depends on `libopencv-dev`.
https://github.com/jsk-ros-pkg/jsk_3rdparty/blob/f2b2bd8ac30a8539a6e099dfe7f1e2830ca12430/3rdparty/libcmt/package.xml#L13
And on kinetic, `libopencv-dev` refers to OpenCV2, so `libcmt` is compiled against OpenCV2 if we install `libcmt` via apt.
```
yutouchimi@libra:~
$ dpkg -l | grep libopencv-dev
ii  libopencv-dev                                    2.4.9.1+dfsg-1.5ubuntu1.1                             amd64        development files for opencv
yutouchimi@libra:~
$ source /opt/ros/kinetic/setup.bash 
yutouchimi@libra:~
$ ldd /opt/ros/kinetic/lib/libcmt.so 
linux-vdso.so.1 =>  (0x00007ffe1f1cf000)
libopencv_video.so.2.4 => …
```
> [libcmt] Support using OpenCV3 in kinetic

- sesame_ros/package.xml
Build of sesame_ros (released in kinetic) is failing on ROS build farm on some architectures.
http://build.ros.org/job/Kbin_uX32__sesame_ros__ubuntu_xenial_i386__binary/
http://build.ros.org/job/Kbin_uxhf_uXhf__sesame_ros__ubuntu_xenial_armhf__binary/
http://build.ros.org/job/Kbin_uxv8_uXv8__sesame_ros__ubuntu_xenial_arm64__binary/
i386:
```
08:08:12 New python executable in /tmp/binarydeb/ros-kinetic-sesame-ros-2.1.14/obj-i686-linux-gnu/venv/bin/python2
08:08:12 Also creating executable in /tmp/binarydeb/ros-kinetic-sesame-ros-2.1.14/obj-i686-linux-gnu/venv/bin/python
08:08:12 Installing setuptools, pkg_resources, pip, wheel...done.
08:08:15 Running virtualenv with interpreter /usr/bin/python2
08:08:24   Failed building wheel for cryptography
08:08:25 Could not build wheels for …
```
> [sesame_ros] Add dependency for building cryptograpy

- respeaker_ros/CMakeLists.txt
install `config` dir in `respeaker_ros`
the config dir is required to install `udev` file
> [respeaker_ros] install config dir in respeaker_ros

- respeaker_ros/package.xml
add `python-pixel-ring-pip` in `respeaker_ros/package.xml`
> [respeaker_ros] add pixel-ring in run_depend of respeaker_ros

- gdrive_ros/CMakeLists.txt
- gdrive_ros/README.md
- gdrive_ros/launch/gdrive_server.launch
- gdrive_ros/node_scripts/gdrive_server_node.py
- gdrive_ros/package.xml
- gdrive_ros/srv/MultipleUpload.srv
- gdrive_ros/srv/Upload.srv
- jsk_3rdprty/package.xml
gdrive_ros is Google Drive upload ros package.
this package is used in go_to_kitchen demo in fetch. https://github.com/jsk-ros-pkg/jsk_robot/pull/1149
> add gdrive_ros package

- sesame_ros/requirements.txt
- add idna==2.7     to cloes ERROR: requests 2.20.0 has requirement idna<2.8,>=2.5, but you'll have idna 2.9 which is incompatible.
-  Bump urllib3 from 1.22 to 1.24.2 in /sesame_ros
Bumps [urllib3](https://github.com/urllib3/urllib3) from 1.22 to 1.24.2.
- [Release notes](https://github.com/urllib3/urllib3/releases)
- [Changelog](https://github.com/urllib3/urllib3/blob/master/CHANGES.rst)
- [Commits](https://github.com/urllib3/urllib3/compare/1.22...1.24.2)
Signed-off-by: dependabot[bot] <support@github.com>
-    Bump requests from 2.19.1 to 2.20.0 in /sesame_ros
Bumps [requests](https://github.com/psf/requests) from 2.19.1 to 2.20.0.
- [Release notes](https://github.com/psf/requests/releases)
- [Changelog](https://github.com/psf/requests/blob/master/HISTORY.md)
- …
> update pip modules for security reason

- ros_speech_recognition/README.md
- ros_speech_recognition/launch/speech_recognition.launch
- ros_speech_recognition/scripts/speech_recognition_node.py
In this pull request, I enable multi channel audio recognition.
if audio topic's channel >= 2, single channel data is taken out from multi channel data.
This feature is based on `respeaker_node.py`, in which 1 channel audio data is taken out from 4 channel respeaker audio.
https://github.com/jsk-ros-pkg/jsk_3rdparty/blob/75e5e7ed0f650bffd1d434e522a72466be9735f7/respeaker_ros/scripts/respeaker_node.py#L278-L280
I was careful not to use numpy, which is additional dependency.
> [ros_speech_recognition] Enable multi channel audio recognition

- gdrive_ros/node_scripts/gdrive_server_node.py
with this PR, gdrive_ros catches file not found error with `OSError` and log error properly.
this PR has two commits:
- raise `OSError` when uploading file is not found and catch it
- fix `rospy.logerr` format and add `rospy.loginfo` format
> [gdrive_ros] Fix gdrive_ros to catch error properly

- respeaker_ros/scripts/respeaker_node.py
use `rospy.logerr` instead of `print`
this is for ROS logging system
cc. @708yamaguchi
> [respeaker_ros] use rospy.logerr instead of print

- dialogflow_task_executive/README.md
- dialogflow_task_executive/node_scripts/task_executive.py
with this PR, dialogflow can use full name of app name (`<package name>/<app name>`) for dialoglow action.
I'm testing this PR on pr1040 now.
> [dialogflow_task_executive] accepct full name of app name for dialogflow action

- respeaker_ros/README.md
- respeaker_ros/package.xml
1. Change the name of sample launch file in README.md.
2. Add speech_recognition_msgs to package.xml because it is used in speech_to_text.py
https://github.com/jsk-ros-pkg/jsk_3rdparty/blob/master/respeaker_ros/scripts/speech_to_text.py#L15
> Mistakes I found when I tried to use respeaker_ros on hirovision

- .travis.yml
- ros_speech_recognition/CMakeLists.txt
- ros_speech_recognition/src/ros_speech_recognition/__init__.py
I use python 3 in virtualenv in ros_speech_recognition to avoid the below error.
```
[ros_speech_recognition:make] Traceback (most recent call last):
[ros_speech_recognition:make]   File "/home/travis/ros/ws_jsk_3rdparty/src/jsk_3rdparty/ros_speech_recognition/scripts/speech_recognition_node.py", line 5, in <module>
[ros_speech_recognition:make]     import actionlib
[ros_speech_recognition:make]   File "/opt/ros/noetic/lib/python3/dist-packages/actionlib/__init__.py", line 28, in <module>
[ros_speech_recognition:make]     from actionlib.action_client import *
[ros_speech_recognition:make]   File "/opt/ros/noetic/lib/python3/dist-packages/actionlib/action_client.py", line 56, in <module>
[ros_speech_recognition:make]     import rospy
[ros_speech_recognition:make]   File …
```
> Fix travis

- 3rdparty/voice_text/.gitignore
- 3rdparty/voice_text/CMakeLists.txt
- 3rdparty/voice_text/README.md
- 3rdparty/voice_text/launch/voice_text.launch
- 3rdparty/voice_text/src/voice_text.cpp.in
We bought a new VoiceText SDK whose speaker is RISA and tried to use voice_text package with that SDK.
However, current voice_text assumes that the speaker is SAYAKA:
https://github.com/jsk-ros-pkg/jsk_3rdparty/blob/bfce3ffc368bfb9367bd429a289aee36c1bbc0d2/3rdparty/voice_text/CMakeLists.txt#L28
https://github.com/jsk-ros-pkg/jsk_3rdparty/blob/bfce3ffc368bfb9367bd429a289aee36c1bbc0d2/3rdparty/voice_text/src/voice_text.cpp#L24
https://github.com/jsk-ros-pkg/jsk_3rdparty/blob/bfce3ffc368bfb9367bd429a289aee36c1bbc0d2/3rdparty/voice_text/src/voice_text.cpp#L35
https://github.com/jsk-ros-pkg/jsk_3rdparty/blob/bfce3ffc368bfb9367bd429a289aee36c1bbc0d2/3rdparty/voice_text/launch/voice_text.launch#L16
In addition, the new VoiceText SDK has a different directory tree from the old one (e.g., …
> [voice_text] Support other speakers than SAYAKA and new directory tree

- 3rdparty/aques_talk/README.md
- 3rdparty/aques_talk/text2wave
I replace numbers in text file for aques_talk to speak numbers. I add sed command like following.
```
$ echo こんにちわ | sed -e 's/\([a-zA-Z]\+\)/<ALPHA VAL=\1>/g' | sed -e 's/\([0-9]\+\)/<NUMK VAL=\1>/g'
こんにちわ
$ echo 私の名前わ、fetch15です。 | sed -e 's/\([a-zA-Z]\+\)/<ALPHA VAL=\1>/g' | sed -e 's/\([0-9]\+\)/<NUMK VAL=\1>/g'
私の名前わ、<ALPHA VAL=fetch><NUMK VAL=15>です。
```
For example, 
```bash
$ roslaunch aques_talk aques_talk.launch
$ rostopic pub /robotsound_jp  sound_play/SoundRequest "{sound: -3, command: 1, volume: 10.0, arg: '私の名前わ、fetch15です。', arg2: ''}"
```
> Replace numbers and alphabets in text file for aques_talk to speak numbers

- gdrive_ros/CMakeLists.txt
- gdrive_ros/launch/gdrive_server.launch
moved from #231 
this PR fixes the typo.
I also add `roslaunch` test recommended by @708yamaguchi in https://github.com/jsk-ros-pkg/jsk_3rdparty/pull/231#pullrequestreview-563448623
@sktometometo thank you for fixing the typo.
> [gdrive_ros] fix typo and add roslaunch test

- gdrive_ros/launch/gdrive_server.launch
I add `node_name` argument to `gdrive_server.launch` to avoid node's name collision
> [gdrive_ros] add node_name arg in gdrive_server.launch

- .travis.yml
To pass travis tests in jsk_3rdparty
https://travis-ci.com/github/jsk-ros-pkg/jsk_3rdparty/builds/217741761
```
+ sudo -E python
+ curl https://bootstrap.pypa.io/get-pip.py
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 1884k  100 1884k    0     0  4795k      0 --:--:-- --:--:-- --:--:-- 4795k
Traceback (most recent call last):
File "<stdin>", line 24244, in <module>
File "<stdin>", line 199, in main
File "<stdin>", line 82, in bootstrap
File "/tmp/tmpMylbEX/pip.zip/pip/_internal/cli/main.py", line 60
sys.stderr.write(f"ERROR: {exc}")
^
SyntaxError: invalid syntax
```
> update jsk_travis to 0.5.18, fix get-pip.py problem

- respeaker_ros/scripts/speech_to_text.py
Fix default sound_play action name of speech_to_text.py.
By this pr, sample_respeaker.launch will work correctly.
> [respeaker_ros] fix default sound_play action name of speech_to_text.py

- ros_speech_recognition/launch/speech_recognition.launch
- ros_speech_recognition/scripts/speech_recognition_node.py
- ros_speech_recognition/src/ros_speech_recognition/recognize_google_cloud.py
fix load_parameters: unable to set parameters when `roslaunch ros_speech_recognition speech_recognition.launch`
support SpeakerDiarization
- support SpeakerDiarization, see
https://cloud.google.com/speech-to-text/docs/reference/rest/v1/speech/recognize#SpeechRecognitionAlternative
- add doc to args, and we need to use rosparm for device, not param. because
'device: ' causes
>    load_parameters: unable to set parameters (last param was
>    [/speech_recognition/depth=16]): cannot marshal None unless allow_none is
>    enabled
error
- more exception message for self.recognize
> fix load_parameters: unable to set parameters

- respeaker_ros/package.xml
Fixes typo introduced in https://github.com/jsk-ros-pkg/jsk_3rdparty/commit/39be21894a38112a1633cf8385caf079c35536ff
> [respeaker_ros] Specify correct Python version in package.xml

- 3rdparty/aques_talk/README.md
- 3rdparty/aques_talk/text2wave
Please see https://github.com/jsk-ros-pkg/jsk_3rdparty/issues/255
With this pull request, for example,
```
’こ”^＾ん/に*|ち＊＊｜は；：;:『』!！#＃$＄&＆~〜()（）＿_｀\_\\\_・・<\>＊｀＞＜+＋@＠ー=＝
```
is converted to
```
こんにちはー
```
> Ignore charactors which AquesTalk2 cannot recognize and update README.md

- gdrive_ros/README.md
- gdrive_ros/node_scripts/gdrive_server_node.py
try authentication multiple times in gdrive_ros
> [gdrive_ros] try authentication multiple times

- chaplus_ros/CMakeLists.txt
- chaplus_ros/README.md
- chaplus_ros/apikey.json
- chaplus_ros/package.xml
- chaplus_ros/sample/google_example.launch
- chaplus_ros/scripts/chaplus_ros.py
- chaplus_ros/setup.py
see README.md for more information
> add chaplus ros interface

- 3rdparty/slic/CMakeLists.txt
> [slic] fix typo in slic/CMakeLists.txt

- switchbot_ros/launch/switchbot.launch
- switchbot_ros/scripts/switchbot_ros_server.py
Moved from https://github.com/jsk-ros-pkg/jsk_3rdparty/pull/276 .
`SwitchBotAPIClient` class in `switchbot.py` gets the device list from the server when initialized. I forgot catching the network-not-connected exception when it happens so I added it to the rosnode. @knorth55 also added the respawn arg.
> [switchbot_ros] catch the exception when init the node

- webrtcvad_ros/CMakeLists.txt
- webrtcvad_ros/README.md
- webrtcvad_ros/launch/sample.launch
- webrtcvad_ros/node_scripts/print_stt_result.py
- webrtcvad_ros/node_scripts/webrtcad_ros.py
- webrtcvad_ros/node_scripts/webrtcvad_ros.py
- webrtcvad_ros/package.xml
Moved from https://github.com/jsk-ros-pkg/jsk_3rdparty/pull/258
Add webrtcvad_ros package for Voice Activity Detection.
This package provides a wrapper node for [webrtcvad](https://github.com/wiseman/py-webrtcvad) which is for Voice Activity Detection.
It subscribes an audio topic and publish a flag if curretly speeched or not with VAD.
You need a microphone on your computer to use this example.
```bash
roslaunch webrtcvad_ros sample.launch
```
> [webrtcvad_ros] Add webrtcvad_ros package for Voice Activity Detection

- 3rdparty/lpg_planner/CMakeLists.txt
- 3rdparty/lpg_planner/Makefile
- 3rdparty/lpg_planner/lpg1.2-linux.tar.gz.md5sum
- 3rdparty/lpg_planner/package.xml
we need to manually install `lpg` into `~/Downloads` for current lpg_planner.
this PR change the installation and automatically install `lpg` in `catkin build`.
> [lpg_planner] install lpg_planner from jsk-ros-pkg/archieve

- switchbot_ros/CMakeLists.txt
- switchbot_ros/package.xml
- switchbot_ros/scripts/switchbot_ros_server.py
- switchbot_ros/setup.py
- switchbot_ros/src/switchbot_ros/switchbot.py
I use `catkin_setup_python` to make `switchbot_ros` as python package.
This PR avoids relative import in `switchbot_ros_server.py`, which may causes error in python3.
> [switchbot_ros] use python setup to avoid relative import in switchbot_ros

- 3rdparty/google_cloud_texttospeech/README.md
- 3rdparty/google_cloud_texttospeech/bin/text2wave
- 3rdparty/google_cloud_texttospeech/launch/google_cloud_texttospeech.launch
`google cloud texttospeech` waits for a reply of API communication.
It takes a little time and money for the API.
This PR reducess them by adding cache functionality.
The cache is enabled by default.
```
[INFO] [1626084805.085691]: sound_play node is ready to play sound
[Text2Wave] Using cached sound file (/home/iory/.ros/google_cloud_texttospeech/cache/3e1189533149d5b129aa1f6211876962--ja-JP--ja-JP-Wavenet-A--1.0.mp3) for これはテストです
```
> [google_cloud_texttospeech] Add cache option

- 3rdparty/voice_text/launch/voice_text.launch
- 3rdparty/voice_text/src/dummy/vt_dummy.cpp
- 3rdparty/voice_text/src/dummy/vt_dummy.h
- 3rdparty/voice_text/src/voice_text.cpp.in
Recently, when I use voice_text in fetch1075, it says "ライセンスが有効ではありません (License not valid)"
I talked with the manufacturer and they advised me that VT_VERIFY_CODE should be set to not 0 when this problem occurs.
So I made VT_VERIFY_CODE to be displayed when voice_text starts.
Also, the path to the wav file generated by voice_text is now displayed.
If fetch1075 says "ライセンスが有効ではありません (License not valid)" again, please give VT_VERIFY_CODE and the generated wav file to the manufacturer.
@mqcmd196 @tkmtnt7000
> Add verification check rosinfo

- .github/workflows/indigo.yml
- .github/workflows/kinetic-i386.yml
- .github/workflows/kinetic.yml
- .travis.yml
to run `catkin build` instaed of `travis_wait 60 catkin build`
jsk_3rdparty sometime takes more than 60 min for build
> update jsk_travis 0.5.22

- ros_speech_recognition/README.md
- ros_speech_recognition/launch/speech_recognition.launch
- ros_speech_recognition/scripts/speech_recognition_node.py
- ros_speech_recognition/test/sample_ros_speech_recognition.test
Add a flag to enable or disable sound to play sound on recognition and add `play_sound` for continuous recognition mode.
You can select mute or unmute sound effects on speech recognition.
Using test rosbag, you can try this PR.
```
roslaunch ros_speech_recognition sample_ros_speech_recognition.test launch_sound_play:=true
```
> Enable sound play flag

- dialogflow_task_executive/node_scripts/dialogflow_client.py
this PR is split from #313 
this PR loads `project_id` from `credential` json.
with this PR, we only need to pass json path, no need to pass project id.
> [dialogflow_task_executive] load dialogflow project_id from credentials

- switchbot_ros/scripts/switchbot_ros_server.py
- switchbot_ros/src/switchbot_ros/switchbot.py
When publish the switchbot control action topic with switchbot device which not exists 
before this PR
```
[ERROR] [WallTime: 1642402768.977277] [node:/switchbot_ros] [func:SwitchBotAction.execute_cb]: '/eng2/7f/73b2/light/upper/switch'
```
after this PR
```
[ERROR] [WallTime: 1642405853.687783] [node:/switchbot_ros] [func:SwitchBotAction.execute_cb]: 'Device name:/eng2/7f/73b2/light/upper/switch is not registered at switchbot server. Please check the setting.'
```
and also returns the action feedback status.   
In addition I removed catching base exception part. cc:@708yamaguchi @tkmtnt7000
> [switchbot_ros] remove catching base exception and output more specific key error when the switchbot id not exists on the server

- dialogflow_task_executive/node_scripts/dialogflow_client.py
Original code raises the error because https://github.com/jsk-ros-pkg/jsk_3rdparty/blob/712cf105484c334a8f6e680176b72b76c7bc0f33/dialogflow_task_executive/node_scripts/dialogflow_client.py#L165 . `data` is not defined.
> [dialogflow_task_executive] Fix bugs when subscribing /text (std_msgs/String) topic

- .gitmodules
Test fails following error
```
Submodule '.travis' (git://github.com/jsk-ros-pkg/jsk_travis) registered for path '.travis'
Cloning into '/__w/jsk_3rdparty/jsk_3rdparty/.travis'...
fatal: remote error: 
The unauthenticated git protocol on port 9418 is no longer supported.
Please see https://github.blog/2021-09-01-improving-git-protocol-security-github/ for more information.
fatal: clone of 'git://github.com/jsk-ros-pkg/jsk_travis' into submodule path '/__w/jsk_3rdparty/jsk_3rdparty/.travis' failed
Failed to clone '.travis'. Retry scheduled
Cloning into '/__w/jsk_3rdparty/jsk_3rdparty/.travis'...
fatal: remote error: 
The unauthenticated git protocol on port 9418 is no longer supported.
Please see https://github.blog/2021-09-01-improving-git-protocol-security-github/ for more information. …
```
> fix jsk_travis

- dialogflow_task_executive/README.md
- dialogflow_task_executive/package.xml
- add comment on how to use roslaunch argument
- dialogflow_task_executive: add speech_recognition_msgs, which is used in  node_scripts/dialogflow_client.py
> dialogflow_task_executive: more depends and udpate README.md

- ros_speech_recognition/launch/speech_recognition.launch
Fixed the behavior when `launch_audio_capture`=true and `audio_topic` are specified.
```
roslaunch ros_speech_recognition speech_recognition.launch audio_topic:=audio_bt continuous:=true language:=ja-JP launch_sound_play:=false launch_audio_capture:=true
```
> [ros_speech_recognition] Fixed the behavior of launch file

- respeaker_ros/scripts/respeaker_node.py
When respeaker_ros is started without setting udev-rules, the command to set udev-rules is displayed as follows.
```bash
[ERROR] [1655343700.794731] [/respeaker_node]: You have to give the right permission on respeaker device
[ERROR] [1655343700.796945] [/respeaker_node]: Please run the command as followings to register udev rules
[ERROR] [1655343700.799090] [/respeaker_node]: 
$ roscd respeaker_ros
$ sudo cp -f $(rospack find respeaker_ros)/config/60-respeaker.rules /etc/udev/rules.d/60-respeaker.rules
$ sudo systemctl restart udev
Traceback (most recent call last):
File "/home/tsukamoto/ros/vendingmachine_demo_ws/src/jsk_3rdparty/respeaker_ros/scripts/respeaker_node.py", line 446, in <module>
n = RespeakerNode()
File "/home/tsukamoto/ros/vendingmachine_demo_ws/src/jsk_3rdparty/respeaker_ …
```
> [respeaker_ros] Display helpful setting command when udev rule is not set.

- respeaker_ros/README.md
This PR adds documentation for getting readable Japanese voice recognition results from `rostopic echo`.
Users sometimes had a problem that they don't know making Japanese voice recognition results readable through `rostopic echo` and where the example code is.
```
$ rostopic echo --filter "print(m.transcript[0])" /speech_to_text
こんにちは
```
c.f. https://github.com/jsk-ros-pkg/jsk_demos/issues/1347#issuecomment-965031001, https://github.com/jsk-ros-pkg/jsk_demos/issues/1347#issuecomment-965044286
```
k-okada@p51s:~$ rostopic echo /text
data: !!python/str "\u3053\u3093\u306B\u3061\u306F 1636542913.42"
---
data: !!python/str "\u3053\u3093\u306B\u3061\u306F 1636542913.52"
^Ck-okada@p51s:~$ rostopic echo /text | ascii2uni -a U -q
data: !!python/str "こんにちは 1636542916.02"
```
```
rostopic echo …
```
> [respeaker_ros] Add documentation for displaying Japanese `/speech_to_text`

- dialogflow_task_executive/.gitignore
add `requirements.txt` in `.gitignore`
catkin_virtualenv generates `requirements.txt` so I add the file in `.gitignore`.
> [dialogflow_task_executive] add requirements.txt in .gitignore

- dialogflow_task_executive/requirements.txt.indigo
`#### this is only sed for indigo (pr2)` -> `#### this is only used for indigo (pr2)`
> fix type on dialogflow_task_executive/requirements.txt.indigo

- switchbot_ros/CMakeLists.txt
- switchbot_ros/package.xml
this PR solve #356 
add `actionlib_msgs` and `std_msgs` as `build_depend`.
these packages are used in `CMakeLists.txt`.
https://github.com/jsk-ros-pkg/jsk_3rdparty/blob/f0ab7bba54523b8f9945ed4a3e9c0efec0c8dde9/switchbot_ros/CMakeLists.txt#L23-L27
> [switchbot_ros] add actionlib_msgs and std_msgs as build_depend

- dialogflow_task_executive/node_scripts/dialogflow_client.py
This is my fault... 
Output to logwarn when dialogflow returns `input.unknown` . Without this PR, it warns when dialogflow **doesn't return** `input.unknown`
> [dialogflow_task_executive] fix warn bug when got unknown action

- dialogflow_task_executive/CMakeLists.txt
- dialogflow_task_executive/launch/dialogflow_ros.launch
- dialogflow_task_executive/launch/dialogflow_task_executive.launch
- dialogflow_task_executive/node_scripts/dialogflow_client.py
- dialogflow_task_executive/package.xml
- Fixing missing args in `dialogflow_ros.launch` (e27c514504b0db6ff0e0b8238c8fd4a6ac0e2778, 6456fdc6a5bb668c5e002666344ad87e119486a7)
- Adding `always_publish_result` param, for publishing dialogflow result topic even the node gets actionlib request (3f02199f3387c764872eaf81e6c24910a8c6ff2e)
TODO
> [dialogflow_task_executive] adding some args in dialogflow_ros.launch

- rostwitter/scripts/tweet.py
Duplicates of https://github.com/knorth55/jsk_3rdparty/pull/33
This PR suppresses tweet log.
If Base64 encoding texts are displayed in logs, logs are too dirty to see.
> [rostwitter] Suppress tweet log

- google_chat_ros/requirements.in
fix error on CI
```
2023-01-25T02:45:19.9167143Z                                                                                 
2023-01-25T02:45:19.9168296Z [google_chat_ros:make] [31mCould not find a version that matches protobuf!=3.20.0,!=3.20.1,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<4.0.0dev,<5.0.0dev,<=3.19.4,>=3.12.0,>=3.15.0,>=3.19.5 (from -r requirements.in (line 16))
2023-01-25T02:45:19.9168860Z 
2023-01-25T02:45:19.9169092Z                                                                                 
2023-01-25T02:45:19.9170067Z [google_chat_ros:make] Tried: 2.0.3, 2.3.0, 2.4.1, 2.5.0, 2.6.0, 2.6.1, 3.0.0, 3.0.0, 3.1.0, 3.1.0.post1, 3.1.0.post1, 3.2.0, 3.2.0, 3.3.0, 3.4.0, 3.4.0, 3.5.0.post1, 3.5.0.post1, 3.5.1, 3.5.1, 3.5.2, 3.5.2, 3.5.2.post1, 3.5.2.post1, 3.6.0, …
```
> fix google_chat_ros noetic build errors

- ros_speech_recognition/README.md
- ros_speech_recognition/launch/speech_recognition.launch
- ros_speech_recognition/scripts/speech_recognition_node.py
- ros_speech_recognition/test/sample_ros_speech_recognition.test
this PR changes the default value for `speech_recognition.launch`.
with this change, speech_recognition.launch automatically starts and recognized results are published in /speech_to_text topic.
without this PR, we need to run `rosservice call /~~~` to start `speech_recognition` node and the output topic is published in `/Tablet/voice`.
> [ros_ speech_recognition] update default arg for speech_recognition.launch

- gdrive_ros/node_scripts/gdrive_server_node.py
in python3, `sys.version` cannot be compared with int `3`.
this PR fixes the issue.
```python
In [4]: sys.version_info < 3                       
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-4-4a285b5ed8a1> in <module>
----> 1 sys.version_info < 3
TypeError: '<' not supported between instances of 'sys.version_info' and 'int'
```
```python
In [5]: sys.version_info.major < 3                 
Out[5]: False
```
> [gdrive_ros] fix sys.version error

- respeaker_ros/scripts/respeaker_node.py
when the device is not found, the raised error is `FileNotFoundError`, not `IOError` in Python3.
this PR changes to catch the `FileNotFoundError`.
> [respeaker_ros] add FileNotFoundError in respeaker for python3

- 3rdparty/zdepth/package.xml
- zdepth_image_transport/package.xml
the version number of `zdepth` and `zdepth_image_transport` is now `0.0.0`.
this PR change it to `2.1.24`, same as `jsk_3rdparty`.
> [zdepth, zdepth_image_transport] fix zdepth package version to 2.1.24

- zdepth_image_transport/README.md
this PR add readme doc for zdepth_image_transport.
you can check the doc from the link below.
https://github.com/knorth55/jsk_3rdparty/blob/zdepth-readme/zdepth_image_transport/README.md
> [zdepth_image_transport] add readme for zdepth_image_transport

- ros_speech_recognition/scripts/speech_recognition_node.py
Speech recognition result came to return empty list `[]` by https://github.com/jsk-ros-pkg/jsk_3rdparty/pull/434 and it causes the following error. 
`[ERROR] [1678890951.445378]: Unexpected error: (<type 'exceptions.TypeError'>, TypeError('list indices must be integers, not str',), <traceback object at 0x7f5168a77f00>)`
I fixed it.
> [ros_speech_recognition] Return if result is empty

- rostwitter/scripts/tweet_image_server.py
this PR change to use `sub` instead of `self.sub`.
with this chage, `sub` will always be removed when `callback` exits.
this prevents subscribing the topic forever.
> [rostwitter] use sub and not delete

- dialogflow_task_executive/node_scripts/dialogflow_client.py
in python3, `sys.version` is `str`, so we cannot compare `str` and `int`.
this PR fix to use `sys.version_info.major`, which is `int`
```
[rosout][ERROR] 2023-03-25 23:23:33,705: '<=' not supported between instances of 'str' and 'int'
```
> [dialogflow_task_executive] fix typo in dialogflow_client.py

- dialogflow_task_executive/node_scripts/task_executive.py
`map` is not evaluated in `task_executive.py`, which cause the error in python3.
this PR use `list` instead of `map` for python3
```
[rosout][ERROR] 2023-03-26 00:07:22,324: bad callback: <bound method TaskExecutive.dialog_cb of <__main__.TaskExecutive object at 0x7f34b97ad820>>
Traceback (most recent call last):                                                                   
File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 750, in _invoke_callback     
cb(msg)                                        
File "/home/applications/ros/noetic/src/jsk-ros-pkg/jsk_3rdparty/dialogflow_task_executive/node_scripts/task_executive.py", line 190, in dialog_cb
if not self.is_idle:                                                                             
File …
```
> [dialogflow_task_executive] not use map for python3 in task_executive

- ros_speech_recognition/package.xml
Add `ubuntu-sounds` dependency to fix https://github.com/jsk-ros-pkg/jsk_3rdparty/issues/452.
Wait for merging https://github.com/ros/rosdistro/pull/36857
> [ros_speech_recognition] add ubuntu-sounds dependency

- ros_speech_recognition/scripts/parrot_node.py
add `self.conf_thresh` in __init__ function. If it doesn't include this variable in __init__, parrot.launch doesn't print recognized words.
> add self.conf_thresh in __init__ function

- influxdb_store/package.xml
Waiting for https://github.com/ros/rosdistro/pull/36912 to be merged.
Fix the error below:
```
Traceback (most recent call last):
File "/tmp/ros_buildfarm/scripts/doc/create_doc_task_generator.py", line 21, in <module>
run_module('ros_buildfarm.scripts.doc.create_doc_task_generator', run_name='__main__')
File "/usr/lib/python3.8/runpy.py", line 210, in run_module
return _run_code(code, {}, init_globals, run_name, mod_spec)
File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
exec(code, run_globals)
File "/tmp/ros_buildfarm/ros_buildfarm/scripts/doc/create_doc_task_generator.py", line 714, in <module>
sys.exit(main())
File "/tmp/ros_buildfarm/ros_buildfarm/scripts/doc/create_doc_task_generator.py", line 561, in main
debian_pkg_names_depends = resolve_names(depends, **context)
File …
```
> [influxdb_store] fix package deps for python3

- dialogflow_task_executive/README.md
- dialogflow_task_executive/launch/dialogflow_ros.launch
- dialogflow_task_executive/launch/dialogflow_task_executive.launch
- dialogflow_task_executive/node_scripts/dialogflow_client.py
if we have google credential file
```
{
"type": "service_account",
"project_id": "foo",
...
}
```
and use launch file such as
```
<include file="$(find dialogflow_task_executive)/launch/dialogflow_ros.launch">
<arg name="credential" value="$(arg google_credentials_json)" />
<arg name="project_id" value="bar" />
</launch>
```
it still uses `foo` project.
This PR override credential setting and use `project_id` from rosparam.
This PR changes existing launch files that wrongly set `project_id` in launch file, which was ignored, will be effective.
> [API Change] use project_id from json, instead of credentials

- respeaker_ros/scripts/respeaker_node.py
- respeaker_ros/src/respeaker_ros/__init__.py
- respeaker_ros/test/test_rospy_node.py
CI passed version of  #477
0a69e2dc (Kei Okada, 6 seconds ago)
respeaker_ros: Fix test. Not sure why, but #477 did not pass test, we use  rosrun to run scripts
a2174a7d (Soonhyo Kim, 29 hours ago)
[respeaker_ros] importing does not succeed
> [respeaker_ros] importing does not succeed

- 3rdparty/julius/Makefile.dictation-kit
- 3rdparty/julius/Makefile.grammar-kit
- 3rdparty/julius/Makefile.julius
- 3rdparty/zdepth/package.xml
165fe7fb (Kei Okada, 89 seconds ago)     julius: fix location URLs, because osdn is too slow
231fbf4c (Kei Okada, 70 minutes ago)     zdepth  ROS_DISTRO needs ros_environment
lpg_planner and respeaker_ros need to skip shdebs  https://github.com/tork-a/jsk_3rdparty-release/blob/patches/debian/noetic/respeaker_ros/0001-buildfirm-error-due-to-pkg-shlibdeps-error-cannot-fi.patch
> fix build farm

- gdrive_ros/node_scripts/gdrive_server_node.py
before (total time 9.94[sec], without file uploading 6.26[sec])
```
[INFO] [1689163683.613853]: [/gdrive_ros] upload_cb
[INFO] [1689163688.890956]: [/gdrive_ros] Start making a folder: 20230712210803
[INFO] [1689163689.857023]: [/gdrive_ros] Finish making a folder: 20230712210803
[INFO] [1689163689.873074]: [/gdrive_ros] Start uploading a file: hoge.jpg
[INFO] [1689163693.549984]: [/gdrive_ros] Finish uploading a file: hoge.jpg
[INFO] [1689163693.556400]: [/gdrive_ros] Success to upload: /tmp/hoge.jpg -> https://drive.google.com/uc?id=1EC4T445KG388dh-N_-bjAYkMjeXLNYba
```
after (total time 5.82[sec], without file uploading 1.87[sec])
```
[INFO] [1689163736.236137]: [/gdrive_ros] upload_cb
[INFO] [1689163737.118250]: [/gdrive_ros] Start making a folder: 20230712210855
[INFO] …
```
> use query to find folder + title, instead of list all files and apply fileters

- google_chat_ros/scripts/google_chat_ros_node.py
This PR fixes an error message typo, which has an influence on debugging.
> [google_chat_ros] Fix an error message typo; https ==> url

- switchbot_ros/launch/switchbot.launch
- switchbot_ros/scripts/control_switchbot.py
- switchbot_ros/scripts/switchbot_ros_server.py
- switchbot_ros/src/switchbot_ros/switchbot.py
- modifications for SwitchBot API v1.0 and v1.1
- for API v1.0 set only `token` option to `switchbot.launch` the same as before
- for API v1.1 set both `token` and `secret` options to `switchbot.launch` 
- fix codes around infrared remotes and scenes
> Mod for switchbot api 1.1

- .github/workflows/config.yml
- 3rdparty/downward/package.xml
- nfc_ros/CMakeLists.txt
disable installing recommends as ros-o-builder do
> [.github/workflows/config.yml: disable installing recommends in apt-get install

- jsk_ros_patch/collada_urdf_jsk_patch/CMakeLists.txt
now, collada_urdf_jsk_patch is totally dummy package
> [ros-o] collada_urdf_jsk_patch: skip cmake/pkg config generation

- 3rdparty/julius/CMakeLists.txt
- 3rdparty/julius/download_julius_data.sh
- julius_ros/scripts/run_julius.sh
, download dictation and grammer kit by script, because it is too large
```
2025-01-08T11:53:23.9196780Z Dropping build artifacts > 100MB
2025-01-08T11:53:23.9197123Z --------------------------------
2025-01-08T11:53:23.9197670Z + echo Dropping build artifacts > 100MB\n--------------------------------
2025-01-08T11:53:23.9198309Z + find . -type f -size +99M -exec du -h {} ; -exec rm {} ;
2025-01-08T11:53:23.9219197Z 350M       ./ros-one-julius_2.1.29-2-g79210f35-2025.01.08.06.19_amd64.deb
2025-01-08T11:53:23.9857068Z + echo All Debs\n--------
````
> [ros-o] julius: use system install julius

- google_chat_ros/scripts/google-chat.l
this PR marges both #496 and #498
you can write somthing like
```
(setq action goal name "google_chat_ros/send")
(setq ac (instance ros::simple-action-client :init action-goal-name google_chat_ros::SendMessageAction)))
(send-google-chat-text "spaces/AAAARE9CrfA" "Hello" :ac ac)
(send-google-chat-text "spaces/AAAARE9CrfA" "World" :thread-name (send (send ac :get-result) :message_result :thread_name) :ac ac)
```
OR
```
(setq r (send-google-chat-text "spaces/AAAARE9CrfA" "Hello"))
(send-google-chat-text "spaces/AAAARE9CrfA" "World" :thread-name (send r :message_result :thread_name)).
```
> google_chat_ros: enable to get therad_name message result
