.travis.yml
jsk_ros_patch/collada_urdf_jsk_patch/CMakeLists.txt

- [.travis] update to 0.0.5
- [.travis.yml] Add test for jade

add test for jade

---

3rdparty/downward/CMakeLists.txt

source path changed maybe from when we use jsk-ros-pkg/archives

[downward/CMakeLists.txt] fix copy source directory path

---

3rdparty/libcmt/package.xml

From https://github.com/jsk-ros-pkg/jsk_3rdparty/pull/8#issuecomment-138175058

[libcmt] add git depend in package.xml

---

bayesian_belief_networks/setup.py.in

see https://github.com/jsk-ros-pkg/jsk_3rdparty/pull/27#issuecomment-143007535

[bayesian_belief_network] Increase catkin version to fix basename mismatch problem

---

.travis.yml
3rdparty/downward/package.xml

ref: https://github.com/ros/rosdistro/pull/9604

[travis.yml&downward] install time from rosdep instead of travis.yml

---

3rdparty/downward/package.xml

see https://github.com/jsk-ros-pkg/jsk_planning/pull/30#issuecomment-146065373 for failure case

- package.xml : downward uses time command on runnin

---

3rdparty/ffha/Makefile

closes https://github.com/jsk-ros-pkg/jsk_3rdparty/issues/45
Modified:
3rdparty/ffha/Makefile

[ffha] Use http instead of https

---

pgm_learner/package.xml

closes #46
Modified:
pgm_learner/package.xml

[pgm_learner] Depends on rostest

---

bayesian_belief_networks/.gitignore

Modified:
bayesian_belief_networks/.gitignore

[bayesian_belief_networks] Ignore setup.py

---

3rdparty/lpg_planner/CMakeLists.txt
3rdparty/lpg_planner/package.xml

add lpg_planner

---

jsk_3rdprty/package.xml

need to remove sklearn from run_depends in meta package

---

3rdparty/lpg_planner/CMakeLists.txt
3rdparty/lpg_planner/package.xml

add lpg-planner

---

jsk_ros_patch/collada_urdf_jsk_patch/CMakeLists.txt
jsk_ros_patch/collada_urdf_jsk_patch/Makefile

use indigo-devel before changing hydro-devel package structure

---

rostwitter/scripts/tweet.py

please review @furushchev, close #98

rostwitter: fix error message when access token is not found

---

jsk_ros_patch/collada_urdf_jsk_patch/Makefile
jsk_ros_patch/collada_urdf_jsk_patch/use_assimp_devel.patch

- Fix: occasional build failure
- Fix: no notify badge on catkin build in catkin build this package.
This closes #104

[collada_urdf_jsk_patch] fix: occasional build failure

---

3rdparty/voice_text/package.xml

https://github.com/jsk-ros-pkg/jsk_3rdparty/pull/101 needs new dependency

add dynamic_reconfigure to run/build depends

---

3rdparty/julius/package.xml

[julius][package.xml] add rsync to build_depend

---

3rdparty/julius/package.xml

http://build.ros.org/job/Ibin_uT64__julius__ubuntu_trusty_amd64__binary/16/console

add unzip to build_depend

---

3rdparty/voice_text/launch/voice_text.launch

[voice_text] Add respawn argument for sound_play

[voice_text] Add respawn argument for sound_play

---

3rdparty/julius/package.xml

This closes https://github.com/jsk-ros-pkg/jsk_3rdparty/issues/132

julius: add rsync & unzip to run_depend

---

3rdparty/voice_text/CMakeLists.txt
3rdparty/voice_text/src/dummy/vt_dummy.cpp
3rdparty/voice_text/src/dummy/vt_dummy.h
3rdparty/voice_text/src/voice_text.cpp

rewrited version of #131, see https://github.com/jsk-ros-pkg/jsk_3rdparty/pull/131#issuecomment-377932162 for discussion

voice_text: support dynamic linking

---

3rdparty/voice_text/CMakeLists.txt
3rdparty/voice_text/src/voice_text.cpp

followup to #135 - install voice_text TARGETS - voice_text: CMakeLists.txt: remove debug code to force non-exists VT_LIB_PATH

---

3rdparty/julius/package.xml

julius: add wget to dependencies

---

3rdparty/voice_text/CMakeLists.txt

voice_text: add gencfg target to deps

---

respeaker_ros/scripts/respeaker_node.py

`respeaker_node` prints enormous error messages (though it works) every time it launches which makes debugging be really hard.
This pull request is for cleaning up by suppressing the errors.
```bash
$ rosrun respeaker_ros respeaker_node.py 
[INFO] [1537538545.077646] [/respeaker_node:rosout]: Initializing Respeaker device
[INFO] [1537538550.244966] [/respeaker_node:rosout]: Respeaker device initialized (Version: 16)
ALSA lib confmisc.c:768:(parse_card) cannot find card 'Speaker'
ALSA lib conf.c:4248:(_snd_config_evaluate) function snd_func_card_driver returned error: No such device
ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
ALSA lib conf.c:4248:(_snd_config_evaluate) function snd_func_concat returned error: No such device
ALSA lib confmisc.c:1251:(snd_func_refer) …
```

respeaker_ros: cleanup error messages

---

ros_speech_recognition/scripts/speech_recognition_node.py

Should fix GoogleCloud speech recognition

---

.travis.yml

update jsk_travis to 0.5.0

---

respeaker_ros/package.xml
respeaker_ros/scripts/speech_to_text.py
respeaker_ros/test/sample_respeaker.test

c.f.  https://api.travis-ci.org/v3/job/554008643/log.txt
- [respeaker_ros] add python-speechrocognition-pip to package.depends,  because scripts/speech_to_text.py depends on it

[respeaker_ros] increase timeout to pass the test

---

julius_ros/scripts/julius_client.py
ros_speech_recognition/scripts/speech_recognition_node.py

set volume for kinetic
see https://github.com/jsk-ros-pkg/jsk_control/pull/724#issuecomment-513127598 for discussion

add SoundRequest.volume for kinetic

---

3rdparty/ff/package.xml
3rdparty/ffha/package.xml
3rdparty/lpg_planner/package.xml
3rdparty/mini_maxwell/package.xml
3rdparty/nlopt/package.xml

- remove whitespace in <name> section of nlopt/package.xml
- update url/website in package.xml, closes #174

add website to package.xml

---

jsk_3rdprty/package.xml

add dialogflow_task_executive in run_depend of jsk_3rdparty
BTW, jsk_3rdprty :)

[dialogflow_task_executive] add dialogflow_task_executive run_depend in jsk_3rdparty

---

dialogflow_task_executive/package.xml

add url information in `package.xml`

[dialogflow_task_executive] add url in dialogflow_task_executive

---

3rdparty/google_cloud_texttospeech/CMakeLists.txt
3rdparty/google_cloud_texttospeech/README.md
3rdparty/google_cloud_texttospeech/bin/text2wave
3rdparty/google_cloud_texttospeech/launch/google_cloud_texttospeech.launch
3rdparty/google_cloud_texttospeech/package.xml
jsk_3rdprty/package.xml

add `google_cloud_texttospeech` package for ROS + `sound_play` + Google Cloud Text-to-Speech 
this package moves from [itohdak/audio_common@dev](https://github.com/itohdak/audio_common/tree/dev)
cc. @itohdak @iory @nakaotatsuya

[google_cloud_texttospeech] add google_cloud_texttospeech package

---

gdrive_ros/launch/gdrive_server.launch

add `respawn` argument in `gdrive_server.launch`

[gdrive_ros] add argument respawn

---

3rdparty/aques_talk/README.md

I added build procedure for `aques_talk`
@softyanija

Add build procedure for aques_talk

---

gdrive_ros/README.md
gdrive_ros/node_scripts/gdrive_server_node.py

update README.md of gdrive_ros for pip installation.

[gdrive_ros] update README.md

---

rostwitter/scripts/tweet_image_server.py

this PR correctly set actionlib status when error occurs.

[rostwitter] set_aborted when error in tweet_image_server.py

---

respeaker_ros/launch/sample_respeaker.launch
respeaker_ros/scripts/respeaker_node.py
respeaker_ros/scripts/speech_to_text.py

Based on https://github.com/jsk-ros-pkg/jsk_3rdparty/pull/283, I add Python 2.x compatibility.
@dgorissen

respeaker_ros for Python 2.x and 3.x

---

.github/workflows/indigo.yml
.travis.rosinstall.indigo
.travis.yml
rostwitter/CMakeLists.txt
rostwitter/package.xml
rostwitter/python/rostwitter/twitter.py
rostwitter/test/dummy_account.yaml
rostwitter/test/rostwitter.test
rostwitter/test/subscribetest

to catch https://github.com/jsk-ros-pkg/jsk_robot/pull/1342/checks?check_run_id=3579937941
```
[/github/home/ros/ws_jsk_robot/src/jsk_robot/jsk_fetch_robot/jsk_fetch_startup/launch/fetch_bringup.launch]:
cannot find node [tweet_image_server.py] in package [rostwitter]
```

add rostwitter.test

---

gdrive_ros/launch/gdrive_server.launch

add `machine` arg in `gdrive_server.launch`.
cc. @tkmtnt7000

[gdrive_ros] add machine arg in gdrive_server.launch

---

dialogflow_task_executive/node_scripts/dialogflow_client.py

Merging #317 is something wrong.
This PR fixes the incorrect merge.
See also #310

[dialogflow_task_executive] Fix merging #317

---

switchbot_ros/scripts/switchbot_ros_server.py

Sort the displayed device list.
With this PR,
```
[INFO] [1645627852.690941]: Switchbot device list:
Name: /eng2/1f/elevator_bot_up, Type: Bot
Name: /eng2/2f/elevator_HubMini, Type: Hub Mini
Name: /eng2/2f/elevator_bot_up, Type: Bot
Name: /eng2/3f/3felevatorhall_HubMini, Type: Hub Mini
Name: /eng2/3f/door_bot_new, Type: Bot
Name: /eng2/3f/door_bot_old, Type: Bot
Name: /eng2/3f/elevator_bot_up, Type: Bot
Name: /eng2/7f/73b2_bot_kitchen, Type: Bot
Name: /eng2/7f/73b2_bot_window, Type: Bot
Name: /eng2/7f/7felevatorhall_HubMini, Type: Hub Mini
Name: /eng2/7f/elevator_bot_down, Type: Bot
Name: /eng2/7f/elevator_bot_up, Type: Bot
Name: /eng2/8f/elevator_bot_down, Type: Bot
Name: /eng8/1f/elevator_bot_up, Type: Bot
Name: /eng8/1f/elevator_hall, Type: Hub Mini
Name: /eng8/3f/elevator_bot_down, …
```

[switchbot_ros] Sort device_list

---

switchbot_ros/README.md

Update readme to add a link to documents for jsk lab members.

[switchbot_ros] update ReadMe.md

---

chaplus_ros/package.xml
switchbot_ros/package.xml

- install python3-requests in ubuntu focal
- fix wrong package, message_exectime -> message_runtime

[chaplus_ros][switchbot_ros]fix exec_depend in ros noetic

---

switchbot_ros/README.md
switchbot_ros/scripts/switchbot.l
switchbot_ros/src/switchbot_ros/switchbot_ros_client.py

Add `get-devices` to euslisp switchbot_ros client and add python version of `switchbot_ros` client.
```lisp
irteusgl> (load "./switchbot_ros/scripts/switchbot.l")                                                                                                                                                           
6t                                                                                                                                                                                                                
7irteusgl> setq msg (get-devices)                                                                                                                                                                                 
8#<switchbot_ros::devicearray #X55b8ef10aec8> …
```

[switchbot_ros] update switchbot_ros client

---

dialogflow_task_executive/launch/dialogflow_task_executive.launch
dialogflow_task_executive/samples/demo.launch

this PR adds doc in `dialogflow_task_executive` launches

[dialogflow_task_executive] add doc in launch

---

switchbot_ros/package.xml

with this PR, @mqcmd196 can get mail notification from `build.ros.org`.
@mqcmd196 you can realize the package build fails by mail notification.

[switchbot_ros] add obinata as maintainer for switchbot_ros

---

chaplus_ros/README.md
chaplus_ros/scripts/chaplus_ros.py

少し前にA3RTのドメインが変更となっていたため、URLを修正しました。

[chaplus_ros] change a3rt urls

---

3rdparty/aques_talk/CMakeLists.txt

Fix:  https://build.ros.org/job/Mbin_ubv8_uBv8__aques_talk__ubuntu_bionic_arm64__binary/

fix buildfarm errors

---

dialogflow_task_executive/msg/DialogResponse.msg

Adding comments in `DialogResponse.msg`

[dialogflow_task_executive] add comments in DialogResponse.msg

---

.github/workflows/config.yml
dialogflow_task_executive/CMakeLists.txt
dialogflow_task_executive/requirements.in.noetic

- skip X server in 14.04
- fix dialogflow_task_executive compile on noetic

Fix GithubAction

---

.github/workflows/config.yml

This PR is to pass indigo test.

[WIP] fix action@checkout version 3.0.2 

---

google_chat_ros/scripts/google_chat_ros_node.py

[develop/fetch] save google chat image in /chat_notification with timestamp

---

jsk_3rdparty/package.xml

https://github.com/jsk-ros-pkg/jsk_3rdparty/pull/389#issuecomment-1402928748
as mentioned, I listed all enabled packages in jsk_3rdparty and listed in package.xml

[jsk_3rdparty] list all packages in jsk_3rdparty

---

rostwitter/CMakeLists.txt
rostwitter/cfg/TweetImageServer.cfg
rostwitter/package.xml
rostwitter/scripts/tweet_image_server.py

this PR enable to control volume of `tweet_image_server` by `dynamic_reconfigure`.

[tweet_image_server] control volume by dynamic_reconfigure

---

3rdparty/osqp/CMakeLists.txt
3rdparty/osqp/package.xml
jsk_3rdparty/package.xml

Catkinize the external library of OSQP.

[OSQP] add a wrapper package for OSQP, which is a library to solve QP

---

rostwitter/scripts/tweet_image_server.py

current implementation writes image file in subscriber, so the file is updated quickly.
this cause file io error in nfs or network mount system.
this PR changes to write image file after the subscription.

[rostwitter] reduce save file io

---

ros_speech_recognition/CMakeLists.txt
ros_speech_recognition/README.md
ros_speech_recognition/cfg/SpeechRecognition.cfg
ros_speech_recognition/package.xml
ros_speech_recognition/requirements.txt
ros_speech_recognition/requirements.txt.indigo
ros_speech_recognition/scripts/install_trained_data.py
ros_speech_recognition/scripts/speech_recognition_node.py
ros_speech_recognition/src/ros_speech_recognition/recognize_vosk.py
ros_speech_recognition/trained_data/.gitignore

indigo supported version of #462

[ros_speech_recognition] Add vosk engine

---

jsk_3rdparty/package.xml

https://github.com/jsk-ros-pkg/jsk_3rdparty/commit/7cfe72b5b2fdbb5f23988b540eceaaa91384095b

remove rosbuild packages from jsk_3rdparty/package.xml

---

google_chat_ros/scripts/google_chat_ros_node.py

This PR is a develop/fetch version of #492.

[develop/fetch] [google_chat_ros] Fix an error message typo; https ==> url

---

ros_speech_recognition/README.md

Fix typo: fix the message name from `sound_recognition_msgs` to `speech_recognition_msgs` and some typos.
(reference of rosmsg list)
```
actionlib/TestAction
actionlib/TestActionFeedback
actionlib/TestActionGoal
actionlib/TestActionResult
actionlib/TestFeedback
actionlib/TestGoal
actionlib/TestRequestAction
actionlib/TestRequestActionFeedback
actionlib/TestRequestActionGoal
actionlib/TestRequestActionResult
actionlib/TestRequestFeedback
actionlib/TestRequestGoal
actionlib/TestRequestResult
actionlib/TestResult
actionlib/TwoIntsAction
actionlib/TwoIntsActionFeedback
actionlib/TwoIntsActionGoal
actionlib/TwoIntsActionResult
actionlib/TwoIntsFeedback
actionlib/TwoIntsGoal
actionlib/TwoIntsResult
actionlib_msgs/GoalID
actionlib_msgs/GoalStatus
actionlib_msgs/GoalStatusArray …
```

[Typo]fix typo in jsk_3rdparty/ros_speech_recognition/README.md

---

bayesian_belief_networks/Makefile.bayesian

checked with 'git clean -xfd .; bloom-generate rosdebian --os-name=ubuntu --os-version=noble --ros-distro one  --skip-pip; dpkg-buildpackage -b -us -u'

bayesian_belief_networks: fix deb build

---

3rdparty/aques_talk/CMakeLists.txt

Fix the issue introduced in https://github.com/jsk-ros-pkg/jsk_robot/issues/1939#issuecomment-2816634025

[aques_talk] fix python shebang issue
